const $=id=>document.getElementById(id);const today=new Date();const dateKey=today.toLocaleDateString('sv-SE');
$('todayLabel').textContent=new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(today);
const messages=['焦らず一歩ずつ進むことで、思いがけない追い風が吹きます。丁寧な返事と笑顔が幸運を呼ぶ日です。','直感が冴える日。気になったことは、小さく試すことで新しい発見につながります。','周囲との協力が運気を高めます。ひとりで抱え込まず、素直に頼ることが成功への近道です。','過去の努力が形になりやすい日。自分を信じ、いつもより少し大胆に行動してみましょう。','心と環境を整えることで運が開けます。机の上やスマホの整理から始めてみましょう。','大切な人との会話にヒントがあります。相手の言葉を最後まで聞くことで良い流れが生まれます。'];
const actions=['玄関を整えてから外出する','温かい飲み物をゆっくり味わう','気になる人へ短い連絡を送る','不要な写真を10枚整理する','いつもと違う道を歩く','感謝を一つ言葉にする'];
const colors=['ラベンダー','ネイビー','ローズピンク','エメラルド','ゴールド','スカイブルー','アイボリー'],items=['ハンカチ','腕時計','小さなノート','お気に入りのペン','丸いアクセサリー','ミント菓子','水筒'];
const ranks=[{min:92,label:'超大吉'},{min:82,label:'大吉'},{min:70,label:'中吉'},{min:58,label:'小吉'},{min:45,label:'吉'},{min:0,label:'末吉'}];
const tarot=[['☀️','太陽','喜びと成功。前向きな気持ちが道を照らします。'],['🌙','月','曖昧さと直感。結論を急がず心の声を確かめて。'],['⭐','星','希望と回復。小さな願いを行動へ変える時です。'],['🌿','節制','調和と継続。無理のないバランスが成果を育てます。'],['🦁','力','内なる強さ。優しさと落ち着きで状況を動かせます。'],['🎡','運命の輪','転機の到来。偶然の誘いに良い流れが隠れています。'],['🧙','魔術師','始まりと創造。手元にある力を使えば形にできます。'],['⚖️','正義','公平と判断。感情と事実を分けて考えると答えが見えます。'],['🌍','世界','完成と達成。積み重ねた努力が一つの成果になります。']];
const omikuji=[['大大吉','願いが形になりやすい特別な日。遠慮せず一歩踏み出して。'],['大吉','良い流れが来ています。周囲への感謝が運をさらに育てます。'],['中吉','穏やかな上昇運。焦らず続けることで結果がついてきます。'],['小吉','小さな幸運を見逃さないで。身近な人の言葉がヒントです。'],['吉','落ち着いた一日。準備と確認を丁寧にすると安心です。'],['末吉','これから運が開く時。今日は無理をせず土台を整えましょう。']];
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h>>>0)}function seeded(s,min,max){return min+hash(s)%(max-min+1)}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function zodiac(v){if(!v)return'星座未設定';const d=new Date(v),m=d.getMonth()+1,day=d.getDate(),signs=['山羊座','水瓶座','魚座','牡羊座','牡牛座','双子座','蟹座','獅子座','乙女座','天秤座','蠍座','射手座'],cut=[20,19,21,20,21,22,23,23,23,24,23,22];return day<cut[m-1]?signs[m-1]:signs[m%12]}
function addHistory(type,title,score){let a=JSON.parse(localStorage.getItem('uranaiHistory')||'[]');a.unshift({date:dateKey,type,title,score});localStorage.setItem('uranaiHistory',JSON.stringify(a.slice(0,15)));renderHistory()}
function renderHistory(){const a=JSON.parse(localStorage.getItem('uranaiHistory')||'[]'),b=$('historyList');b.innerHTML=a.length?a.map(x=>`<div class="history-item"><div><b>${x.type}</b><br><small>${x.date}・${x.title}</small></div><div class="history-score">${x.score||'✦'}</div></div>`).join(''):'<p class="empty">まだ履歴はありません。</p>'}
function switchTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===id));scrollTo({top:120,behavior:'smooth'})}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
$('fortuneBtn').onclick=()=>{const name=$('nameInput').value.trim()||'あなた',birth=$('birthdayInput').value,blood=$('bloodInput').value||'未設定',theme=$('themeInput').value,base=`${dateKey}|${name}|${birth}|${blood}|${theme}`,score=seeded(base+'main',52,99),detail={恋愛:seeded(base+'love',45,99),仕事:seeded(base+'work',45,99),金運:seeded(base+'money',45,99),健康:seeded(base+'health',45,99)},rank=ranks.find(r=>score>=r.min).label;localStorage.setItem('uranaiProfile',JSON.stringify({name,birth,blood,theme}));$('dailyResult').classList.remove('hidden');$('resultTitle').textContent=`${name}さんの${theme}`;$('scoreValue').textContent=score;$('rankBadge').textContent=rank;$('mainMessage').textContent=`${zodiac(birth)}の${name}さんへ。${messages[hash(base+'msg')%messages.length]}`;$('scoreRing').style.background=`conic-gradient(var(--gold) ${score}%,rgba(255,255,255,.12) 0)`;$('meters').innerHTML=Object.entries(detail).map(([k,v])=>`<div class="meter"><span>${k}</span><div><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('');$('luckyColor').textContent=colors[hash(base+'c')%colors.length];$('luckyItem').textContent=items[hash(base+'i')%items.length];$('luckyNumber').textContent=seeded(base+'n',1,9);$('luckyTime').textContent=`${seeded(base+'h',7,20)}:${['00','15','30','45'][seeded(base+'m',0,3)]}`;$('actionText').textContent=actions[hash(base+'a')%actions.length];window.currentText=`【星しずく占い＋】${name}さんの${theme}は${rank}・${score}点！`;addHistory('今日の運勢',`${name}さん・${rank}`,`${score}点`);$('dailyResult').scrollIntoView({behavior:'smooth'})};
$('shareBtn').onclick=async()=>{try{navigator.share?await navigator.share({title:'星しずく占い＋',text:window.currentText}):await navigator.clipboard.writeText(window.currentText);toast('結果を共有できます')}catch{}};$('favoriteBtn').onclick=()=>toast('お気に入りに保存しました');
$('compatBtn').onclick=()=>{const a=$('myName').value.trim()||'あなた',b=$('partnerName').value.trim()||'お相手',base=[a,b,$('myBirth').value,$('partnerBirth').value].sort().join('|'),s=seeded(base,48,99),msgs=['言葉にしなくても通じ合いやすい相性です。共通の楽しみを増やすほど絆が深まります。','違いがあるからこそ成長できる関係。相手の考えを否定せず聞くことが鍵です。','穏やかで安心感のある組み合わせ。小さな感謝を伝えると長続きします。','刺激を与え合える相性です。互いの自由な時間も大切にすると好循環になります。'];$('compatResult').classList.remove('hidden');$('compatTitle').textContent=`${a}さん × ${b}さん`;$('compatScore').textContent=s;$('compatMessage').textContent=msgs[hash(base+'msg')%msgs.length];$('compatAdvice').textContent=['一緒に新しい場所へ出かける','短くても毎日会話する','相手の長所を言葉で伝える','結論より気持ちを先に共有する'][hash(base+'ad')%4];addHistory('相性占い',`${a}さんと${b}さん`,`${s}%`)};
$('nameBtn').onclick=()=>{const n=$('nameFortuneInput').value.trim();if(!n)return toast('名前を入力してください');const traits=['行動力','思いやり','創造力','誠実さ','直感力','協調性','探究心','決断力'],a=[traits[hash(n)%traits.length],traits[hash(n+'2')%traits.length],traits[hash(n+'3')%traits.length]];$('nameResult').classList.remove('hidden');$('nameSymbol').textContent=['✦','☾','♢','∞','❀'][hash(n+'s')%5];$('nameTitle').textContent=`「${n}」が持つ名前の力`;$('nameMessage').textContent=`${n}さんの名前には、人との縁を育てながら自分らしい道を切り開く力が表れています。焦らず得意なことを磨くほど魅力が伝わります。`;$('nameTraits').innerHTML=a.map(x=>`<span class="trait">${x}</span>`).join('');addHistory('名前占い',n,'✦')};
let revealed=0;function setupTarot(){revealed=0;$('tarotSummary').classList.add('hidden');const seed=`${dateKey}|${Date.now()}`,positions=['過去','現在','未来'];$('tarotCards').innerHTML=positions.map((p,i)=>`<button class="tarot-card" data-i="${i}" data-card="${hash(seed+i)%tarot.length}"><div class="back">✦</div><b>${p}</b></button>`).join('');document.querySelectorAll('.tarot-card').forEach(c=>c.onclick=()=>{if(c.classList.contains('revealed'))return;const t=tarot[+c.dataset.card];c.classList.add('revealed');c.innerHTML=`<div style="font-size:2.5rem">${t[0]}</div><h3>${c.querySelector('b')?.textContent||''}・${t[1]}</h3><p>${t[2]}</p>`;revealed++;if(revealed===3){$('tarotSummary').classList.remove('hidden');$('tarotSummaryText').textContent='過去の経験を受け止め、今できることに集中すると、未来の流れが自然に整っていきます。小さな選択を大切にしてください。';addHistory('3枚タロット','過去・現在・未来','✦')}})}setupTarot();$('resetTarotBtn').onclick=setupTarot;
$('omikujiBtn').onclick=()=>{const box=$('omikujiBox');box.classList.remove('shake');void box.offsetWidth;box.classList.add('shake');setTimeout(()=>{const base=`${dateKey}|${Date.now()}`,o=omikuji[hash(base)%omikuji.length];$('omikujiResult').classList.remove('hidden');$('omikujiRank').textContent=o[0];$('omikujiMessage').textContent=o[1];$('omikujiDetails').innerHTML=[['願い事',['叶う兆しあり','焦らず待つ','努力で開く'][hash(base+'w')%3]],['恋愛',['素直さが吉','良縁あり','会話を大切に'][hash(base+'l')%3]],['仕事',['挑戦が吉','確認を丁寧に','協力で前進'][hash(base+'j')%3]],['金運',['小さな節約','臨時運あり','計画が吉'][hash(base+'m')%3]]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');addHistory('おみくじ',o[0],'✦')},550)};
$('themeBtn').onclick=()=>{document.body.classList.toggle('light');const l=document.body.classList.contains('light');$('themeBtn').textContent=l?'☀️':'🌙';localStorage.setItem('uranaiLight',l?'1':'0')};$('clearBtn').onclick=()=>{localStorage.removeItem('uranaiHistory');renderHistory();toast('履歴を消去しました')};
try{const p=JSON.parse(localStorage.getItem('uranaiProfile'));if(p){$('nameInput').value=p.name==='あなた'?'':p.name;$('birthdayInput').value=p.birth||'';$('bloodInput').value=p.blood==='未設定'?'':p.blood;$('themeInput').value=p.theme||'総合運'}}catch{}if(localStorage.getItem('uranaiLight')==='1'){document.body.classList.add('light');$('themeBtn').textContent='☀️'}renderHistory();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
